spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/impl-ddd
    username: eric
    password: evans
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata
  docker:
    compose:
      # Just start compose, so devs can connect to running Postgres instance
      lifecycle-management: start_only

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      apache:
        hc:
          client5:
            http:
              # See: https://hc.apache.org/httpcomponents-client-5.3.x/logging.html
              headers: INFO

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always