spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/impl-ddd
    username: eric
    password: evans
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always